### PR TITLE
Support for password policies

### PR DESCRIPTION
**Pull request by alexwilcox9**
Closes: https://github.com/hashicorp/terraform-provider-azuread/issues/136

@manicminer is this the kind of thing you had in mind? 
One thing I haven't checked is if both are true will graph always return them in that order or should we just check if the string contains `DisablePasswordExpiration`/`DisableStrongPassword` rather than going for an exact match

### CODE REVIEW

**Comment by manicminer** [comment]
@alexwilcox9 This looks good! I think we could probably make them top-level properties like `force_password_change`, there isn't much to gain by putting them in a block?

**Comment by alexwilcox9** [comment]
@manicminer I just love blocks! That's fair enough I've rearranged it a bit now, also not sure what to call the two functions as they're not really expand/flatten functions so suggestions are welcome!

**Comment by manicminer** [comment]
I like blocks too, it's just that they introduce complexity when interacting with the TF plugin SDK :)

To be honest I don't think we need flatten/expand functions in this case, we can do it inline in the create/update funcs without much boilerplate. The only thing I would change with the parsing of the API response for `passwordPolicies` is I would split it into a slice on the comma, and do a case insensitive (space trimmed) comparison with each value, to account for the API reordering or changing them.

**Comment by alexwilcox9** [comment]
Agreed, splitting it into a slice makes more sense. I've scrapped the functions and moved the contents into the create/update/read functions

**Comment by alexwilcox9** [comment]
I've hit a new issue now that I'm hoping you can help advise on.

Currently I set `passwordPolicies` to a pointer to an empty string if neither options are specified however that lead to me getting the following
```
        UsersClient.BaseClient.Post(): unexpected status 400 with OData error:
        Request_BadRequest: Invalid value specified for property 'passwordPolicies'
        of resource 'User'.
```

So I then had the idea to set `passwordPolicies` to nil if neither option were selected which did initially solved the problem but seems to have broken the update function should you go from having either option set to neither of them as sending nil doesn't update the password policies
```
    testcase.go:60: Step 5/6 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azuread_user.test will be updated in-place
          ~ resource "azuread_user" "test" {
              ~ disable_password_expiration = true -> false
              ~ disable_strong_password     = true -> false
                id                          = "b6df9c72-649e-41d3-91fb-fec9461d596e"
                # (16 unchanged attributes hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccUser_update (30.32s)
```

So I can't work out what value you set if you want to turn both options off..

I hope that makes sense! Any ideas?

**Comment by manicminer** [comment]
Hi @alexwilcox9, this is a fairly common issue which can be resolved, but requires a change in the SDK (hamilton). For values that should be unset by sending `null` instead of a blank string, there is a custom type `StringNullWhenEmpty` which should be used instead of a regular `string`.

I've tried to catch as many of these as I can based on documentation, but it doesn't always indicate in the docs. You can fix it in Hamilton and it should solve this.

The line to fix is https://github.com/manicminer/hamilton/blob/main/msgraph/models.go#L1126

It is currently:
```go
	PasswordPolicies                *string                  `json:"passwordPolicies,omitempty"`
```

but it should be:
```go
	PasswordPolicies                *StringNullWhenEmpty     `json:"passwordPolicies,omitempty"`

```

Give me a shout on Slack if I can assist with making this change in your dev environment. I often add a [go.mod override](https://golang.org/ref/mod#go-mod-file-replace) and then vendor from a local copy, and then PR the change in Hamilton once i'm confident it works.

**Comment by alexwilcox9** [comment]
Thanks for the tip and help getting my environment set up, I've created a PR in the SDK repo for this change
https://github.com/manicminer/hamilton/pull/96

**Comment by alexwilcox9** [comment]
Just thinking... whilst I'm at it should I update the user data resource to include these new attributes?

**Review by manicminer — CHANGES_REQUESTED** [review]
This looks and works great, just some minor suggestions on variable naming but otherwise this LGTM 👍

**Review by manicminer — APPROVED** [review]
LGTM 🚀 

Screenshot 2021-09-09 at 23 39 09

**Pull request merged**
