### PR TITLE
[WIP] IdentityGovernance Package (accessPackages / EntitlementMangement)

### LINKED ISSUE #547: Feature Tracker - EntitlementManagment - AccessPackages
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently Developing in Upstream SDK Capability for relevant accessPackage* Resource Types on the Beta API
https://github.com/manicminer/hamilton/issues/92

Leaving a feature tracker here to get feedback / +1s as well as to track progress when downstream work starts

### New or Affected Resource(s)

azuread_access_package
azuread_access_package_catalog
azuread_access_package_assignment_policy

### Potential Terraform Configuration

```hcl
WIP
```

### References

https://github.com/manicminer/hamilton/issues/92
https://github.com/manicminer/hamilton/pull/93

### PR DESCRIPTION
**Pull request by kaovd**
There is a lot of various sub resources in the Identity Governance scope - currently WIP on EntitlementManagement / accessPackages here specifically and introducting the package as it does not exist yet

Closes #547

### CODE REVIEW

**Comment by askew** [comment]
@kaovd , are you still actively working on this PR? We have a need for it and we're looking at picking up your WIP and trying to complete it.

**Comment by kaovd** [comment]
> @kaovd , are you still actively working on this PR? We have a need for it and we're looking at picking up your WIP and trying to complete it.

Will push my latest commit, had a bit of a hiatus for past month, just a few bugs left I hope

**Comment by aleksei-aikashev** [comment]
thank you for your work! we're eagerly waiting for this one to be merged 🙏

**Comment by kaovd** [comment]
@aleksei-aikashev I plan to try and revisit this in coming weeks, I did kind of expect someone to pick this up and fix the remaining bugs but will give it another go

**Comment by askew** [comment]
@kaovd, we have done a fair amount of work on this and have a WIP in the [entitlement-management branch of my fork](https://github.com/askew/terraform-provider-azuread/tree/feature/entitlement-management). It would be good to work with you to get these changes merged into this PR.

**Comment by kaovd** [comment]
> @kaovd, we have done a fair amount of work on this and have a WIP in the [entitlement-management branch of my fork](https://github.com/askew/terraform-provider-azuread/tree/feature/entitlement-management). It would be good to work with you to get these changes merged into this PR.

Thank you! I will take a look today

**Comment by kaovd** [comment]
> @kaovd, we have done a fair amount of work on this and have a WIP in the [entitlement-management branch of my fork](https://github.com/askew/terraform-provider-azuread/tree/feature/entitlement-management). It would be good to work with you to get these changes merged into this PR.

Thank you! I will take a look today

**Comment by kaovd** [comment]
@askew Thanks for some of these fixes - Just one the ConnectedOrganisations resource / Client you've added - I don't see where msgraph.ConnectedOrganization is defined in the SDK unless you've referenced something else locally?

**Comment by askew** [comment]
It's dependent on the upstream change to the Hamilton library https://github.com/manicminer/hamilton/pull/156

**Comment by kaovd** [comment]
Ah ok, forgot to check the drafts - also some enums where missing that would be good to get in the same PR on access package assignment question types (TextInputQuestion, MultipleChoiceQuestion)

**Comment by aleksei-aikashev** [comment]
any updates on this? 🙏

**Comment by stanleyz** [comment]
a bit surprised that I missed this one before starting my work in #903 , anyway raised another one for the implementation there.

**Comment by kaovd** [comment]
Ditching this one in favour of https://github.com/hashicorp/terraform-provider-azuread/pull/903

**Pull request closed without merging**
