### PR TITLE
Docs/app_role_assignment: add example for role assignment to default app role

### PR DESCRIPTION
**Pull request by audunsolemdal**
I didn't find it intuitive how to assign to the default app role, so I added an example.

### CODE REVIEW

**Review by manicminer — CHANGES_REQUESTED** [review]
Thanks for this contribution @audunsolemdal. Would you be able to add a note about the magic default value `00000000-0000-0000-0000-000000000000` to the `app_role_id` property? Thanks!

**Comment by audunsolemdal** [comment]
I was thinking about that, but I am not sure whether this should be as simple comment behind the id
```
app_role_id = "00000000-0000-0000-0000-000000000000" # Default app role
```

Or a note with a reference to Microsoft documentation before the example code starts. What do you think is best?

**Comment by manicminer** [comment]
The example you have put together is great - I don't think it needs a trailing comment given the brevity of the config - but I do think it needs mentioning alongside the property description. Perhaps something like this?

```markdown
`app_role_id` - (Required) The ID of the app role to be assigned, or the default role ID `00000000-0000-0000-0000-000000000000`. Changing this forces a new resource to be created.
```

**Review by manicminer — APPROVED** [review]
Thanks again @audunsolemdal, this LGTM! 👍

**Pull request merged**
