### PR TITLE
Document `keepers` property for application and service principal passwords

### PR DESCRIPTION
**Pull request by manicminer**
Closes: #570

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🩹

**Comment by katbyte** [comment]
thou one might argue that "keepers" is a bad name for this property as how does that equate "rotate password when" 🤔

**Comment by manicminer** [comment]
Yeah it's not the most intuitive name tbf. I took the concept and the naming from the [random provider](https://registry.terraform.io/providers/hashicorp/random/latest/docs#resource-keepers) where it seems to be aiming for a generic approach. Totally happy to rename it to something more specific, though I'm struggling to think of anything good :D

**Comment by katbyte** [comment]
ahh given there is a keeper password manager might be best to change hah, doesn't seem like its a standard term for it? - no reason not to be verbose `rotate_password_when_changed` ?

**Comment by manicminer** [comment]
> ahh given there is a keeper password manager might be best to change hah, doesn't seem like its a standard term for it? - no reason not to be verbose `rotate_password_when_changed` ?

Sounds perfect 👌

**Comment by manicminer** [comment]
@katbyte Have renamed this, do you think we need to support the old property name given that it was undocumented?

**Review by katbyte — APPROVED** [review]
like it! thanks for making that change 🙌  LGTM

**Pull request merged**
