### PR TITLE
Feature: #881 Enable azuread_group to return indirect members

### PR DESCRIPTION
**Pull request by TomasKunka**
#881 
Please have mercy! My first Go code and my first open source contribution.

### CODE REVIEW

**Comment by RichieBzzzt** [comment]
Hello @manicminer I'd also love to see this merged, is there a chance that it will be merged? Thanks in advance!

**Review by manicminer — APPROVED** [review]
Thanks for this contribution @TomasKunka! Apologies for the delay in reviewing the PR - this is an excellent first contribution. I made a couple of minor changes, which ordinarily I'd suggest in my review but given the tardiness of this review, and the diminutive changes needed, I thought it would be helpful to update your branch and note them here.

- We generally prefer to order the attributes in a schema starting with Required properties, followed by Optional ones, and lastly any Computed attributes - with loose secondary ordering by name. I moved the `include_transitive_members` property further up in the schema map, alongside the other Optional properties.
- Where you added an `if` statement to check the value of `include_transitive_members`, I moved the `var err error` statement outside of this `if` block so that it only needs to be declared once. Very much a minor optimization.
- I added the new property to the data source documentation page.

Thank you again for this addition, this LGTM 👍

**Comment by manicminer** [comment]
Test results (failure is unrelated)

Screenshot 2024-05-08 at 20 15 55

**Comment by TomasKunka** [comment]
Thank you for the kind words and thorough explanation @manicminer !

**Pull request merged**
