### PR TITLE
bugfixes for ID parsing

### PR DESCRIPTION
**Pull request by manicminer**
- `data.azuread_group`: fix ID parsing bugs and some panics
- `azuread_conditional_access_policy`: fix parsing bug for `authentication_strength_policy_id`
- `azuread_service_principal_certificate`: fix parsing bug for `service_principal_id`
- `azuread_service_principal_claims_mapping_policy_assignment`: fix parsing bug for `service_principal_id`
- `azuread_service_principal_password`: fix parsing bug for `service_principal_id`
- `azuread_service_principal_token_signing_certificate`: fix parsing bug for `service_principal_id`
- `azuread_synchronization_job`: fix parsing bug for `service_principal_id`
- `azuread_synchronization_job_provision_on_demand`: fix parsing bugs for `service_principal_id` and `synchronization_job_id`
- `azuread_synchronization_secret`: fix parsing bug for `service_principal_id`

and documentation updates

Resolves: #1497
Resolves: #1498

### Conditional Access

Screenshot 2024-09-27 at 14 01 57

### Groups

Failures unrelated.

Screenshot 2024-09-27 at 13 54 30

### Service Principals

Screenshot 2024-09-27 at 13 35 18

### Synchronization

Screenshot 2024-09-27 at 13 41 48

### CODE REVIEW

**Comment by wiebeck** [comment]
Also got ID parsing errors on `azuread_directory_role_assignment` and `azuread_service_principal_delegated_permission_grant`. See https://github.com/hashicorp/terraform-provider-azuread/issues/1497#issuecomment-2379095566

**Review by jackofallops — APPROVED** [review]
Thanks @manicminer - LGTM 👍

**Comment by enorlando** [comment]
hi @manicminer, has the `azuread_service_principal_password` parsing issue been resolved under this PR as we are still getting an error after upgrading to latest provider version 3.0.1

```
Error: parsing "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx": parsing the ServicePrincipal ID: the number of segments didn't match
│ 
│ Expected a ServicePrincipal ID that matched (containing 2 segments):
│ 
│ > /servicePrincipals/servicePrincipalId
│ 
│ However this value was provided (which was parsed into 0 segments):
│ 
│ > xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
│ 
│ The following Segments are expected:
│ 
│ * Segment 0 - this should be the literal value "servicePrincipals"
│ * Segment 1 - this should be the user specified value for this servicePrincipalId [for example "servicePrincipalId"]
│ 
│ The following Segments were parsed:
│ 
│ * Segment 0 - not found
│ * Segment 1 - not found
│ 
│ 
│   with azuread_service_principal_password.xx,
│   on file.tf line 12357, in resource "azuread_service_principal_password" "xxt":
│ 12357:   service_principal_id = azuread_service_principal.xx.object_id
```

**Comment by manicminer** [comment]
@enorlando It should have been resovled - could you post your config?

**Comment by rich-moneybox** [comment]
I'm also seeing a problem with the azuread_service_principal_password:

```
resource "azuread_application" "devops_application" {
  display_name = "devops_test02_application"
}

resource "azuread_service_principal" "devops" {
  client_id = azuread_application.devops_application.client_id
}

resource "azuread_service_principal_password" "client_secret" {
  service_principal_id = azuread_service_principal.devops.id
}
```

This gives issue as described above, e.g.:
```
 Expected a ServicePrincipal ID that matched (containing 2 segments):
│
│ > /servicePrincipals/servicePrincipalId
```

**Comment by manicminer** [comment]
@rich-moneybox You'll need to use the `id` attribute here rather than `object_id`. Please refer to the [documentation for that resource](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal_password#example-usage) for example usage. Thanks!

**Comment by enorlando** [comment]
> @enorlando It should have been resovled - could you post your config?

It seems I was using the wrong attribute ID and required to re import into state the troubled tokenSigningCertificate. Thanks for the assistance

**Comment by leonrob** [comment]
hi @manicminer I think this is still impacting other areas. See https://github.com/hashicorp/terraform-provider-azuread/issues/1553

**Pull request merged**
