### PR TITLE
Add group writeback functionality

### LINKED ISSUE #934: Ability to set "Writeback enabled" on azuread_group resources
Perhaps I am missing something, but I could not find the ability to set the writeback property on azure ad groups in the documentation. This is something that is supported in the api and the UI, can this be set with the provider in some other way?

### PR DESCRIPTION
**Pull request by tomasmota**
Fixes #934

Depends on https://github.com/manicminer/hamilton/pull/199

### CODE REVIEW

**Comment by manicminer** [comment]
@tomasmota I'm keen to get this merged, but I am having issues whilst testing. After enabling writeback for a group, it starts to misbehave and certain requests to GET or PATCH the group start to return a 404 or 403. It seems to be reproducible but I am not sure whether it's something we're doing wrong or whether the API is misbehaving.

I'll dig more into this next week, but for now I have pushed some changes including some docs fixups and bumping Hamilton to pull in the casing fixes.

**Comment by tomasmota** [comment]
Thanks for testing thit out. Have you managed to reproduce it just using hamilton?

**Comment by tomasmota** [comment]
Let me know if there is anything I can do to help troubleshooting this @manicminer

**Comment by manicminer** [comment]
@tomasmota Thanks, at this time I am still having issues whilst testing. I'll have to unfortunately bump to next week but will spend time digging deeper in the meantime.

**Review by manicminer — APPROVED** [review]
@tomasmota Good news, the earlier issues with spontaneous 40x responses seem to be resolved. After rebasing and tweaking the schema, this is working great. Thanks again for working on this 👍

**Comment by manicminer** [comment]
**Test results**

Screenshot 2023-04-13 at 21 38 47

**Pull request merged**
